# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - "lizzcondrey"
      - "bunchw"
    labels:
      - "dependencies"
    groups:
      actions:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - "*"

  
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - "lizzcondrey"
      - "bunchw"
    labels:
      - "dependencies"
    groups:
      runtime_dependencies:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - "runtime_dependencies"
      development_dependencies:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - "development_dependencies"
      documentation_dependencies:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - "documentation_dependencies"     
      test_dependencies:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - "test_dependencies"