name: "💭 Feature Request"
description: Create a new ticket for a new feature request
title: "💭 [REQUEST] - <title>"
labels: [
  "question", 
  "enhancement"
]
projects: [
  "DevOps-MBSE/1"
]
type: "Feature"
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      placeholder: Describe in a few lines your feature request.
    validations:
      required: true
  - type: textarea
    id: dod
    attributes:
      label: "Definition of Done"
      placeholder: Provide a list of criteria by which to judge the effort as done.
    validations:
      required: false
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "What are the drawbacks/impacts of your feature request?"
      placeholder: Identify the drawbacks and impacts while being neutral on your feature request.
    validations:
      required: true
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      placeholder: Identify any unresolved issues.
    validations:
      required: false
  - type: textarea
    id: resources
    attributes:
      label: "Additional Resources"
      placeholder: Provide any additional useful information, guides, or resources for supporting this effort.
    validations:
      required: false
